name: Articles Branch CI

on:
  pull_request:
    branches: ["articles/**"]

jobs:
  make-article:
    runs-on: ubuntu-24.04

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Prepare Variables
        run: |
          if [ "$(uname -m)" = "x86_64" ]; then
            echo "TYPST_ARCH=x86_64-unknown-linux-musl" >> $GITHUB_ENV
          elif [ "$(uname -m)" = "arm64" ]; then
            echo "TYPST_ARCH=aarch64-unknown-linux-musl" >> $GITHUB_ENV
          else
            echo "Unsupported architecture: $(uname -m)"
            exit 1
          fi

      - name: Cache Typst
        uses: actions/cache@v4
        id: typst-cache
        with:
          path: /usr/local/bin/typst
          key: typst-${{ env.TYPST_ARCH }}
          restore-keys: |
            typst-${{ env.TYPST_ARCH }}

      - name: Install Typst
        if: steps.typst-cache.outputs.cache-hit != 'true'
        run: |
          cd /tmp
          curl -sSL $(curl -s https://api.github.com/repos/typst/typst/releases/latest | \
          jq -r '.assets[] | select(.name | contains("'${TYPST_ARCH}'") and endswith(".tar.xz")) | .browser_download_url') \
          -o typst.tar.xz && \
          tar -xvf typst.tar.xz --strip-components 1 && \
          install typst /usr/local/bin && \
          rm typst.tar.xz

      - name: Cache Fonts
        uses: actions/cache@v4
        id: fonts-cache
        with:
          path: |
            fonts
          key: fonts-${{ hashFiles('**/fonts.list') }}
          restore-keys: |
            fonts-${{ hashFiles('**/fonts.list') }}

      - name: Install Fonts
        if: steps.fonts-cache.outputs.cache-hit != 'true'
        run: make setup

      - name: get branch info
        id: branch_info
        shell: bash
        run: |
          BRANCH="${GITHUB_REF#refs/heads/}"
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT
          if [[ "$BRANCH" =~ ^articles/([^/]+)$ ]]; then
            ARTICLE_NAME="${BASH_REMATCH[1]}"
            echo "match=true" >> $GITHUB_OUTPUT
            echo "article_name=$ARTICLE_NAME" >> $GITHUB_OUTPUT
          fi

      - name: compile article
        if: steps.branch_info.outputs.match
        run: |
          cd "${{ steps.branch_info.outputs.branch }}"
          make compile
          mv main.pdf "${{ steps.branch_info.outputs.article_name }}.pdf"

      - name: upload artifact
        id: upload_artifact
        if: steps.branch_info.outputs.match
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.branch_info.outputs.article_name }}.pdf
          path: ${{ steps.branch_info.outputs.branch }}/${{ steps.branch_info.outputs.article_name }}.pdf
          retention-days: 3
          compression-level: 0

      - name: Post a comment
        if: ${{ steps.upload_artifact.outputs.artifact-url }}
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ "${{ steps.upload_artifact.outputs.artifact-url }}" =~ github\.com/([^/]+)/([^/]+)/actions/runs/[0-9]+/artifacts/([0-9]+) ]]; then
            owner="${BASH_REMATCH[1]}"
            repo="${BASH_REMATCH[2]}"
            artifact_id="${BASH_REMATCH[3]}"
            preview_link="（[プレビュー](https://oka4shi.github.io/artifact-previewer/?owner=${owner}&repo=${repo}&artifact_id=${artifact_id})）"
          else
            preview_link=""
          fi
          artifact_link="[${{ steps.branch_info.outputs.article_name }}.pdf](${{ steps.upload_artifact.outputs.artifact-url }})"
          message="記事がビルドされました: ${artifact_link} ${preview_link}"
          set +e
          echo $message | gh pr comment "${{inputs.pr_url }}" -F "-" --edit-last
          if [ $? -ne 0 ]; then
            # コメントが存在しないなどにより失敗した場合は新しく投稿する
            echo $message | gh pr comment "${{inputs.pr_url }}" -F "-"
          fi
          set -e
